--pod wrapper
apiVersion: v1
kind: Pod
metadata:
  name: students-pod
  labels:
      project: students
--container
spec:
  containers:
    - name: student
      image: raptorkuldip/students:latest
      ports:
        - containerPort: 8090